services:
  #python backend
  backend:
    image: getaway-backend-local
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    env_file:
      - .env.local
    networks:
      - getaway-network
  
  frontend:
    image: getaway-frontend-local
    build: ./getaway-web
    ports:
      - "3000:3000"
    volumes:
      - ./getaway-web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - getaway-network
networks:
  getaway-network:
    driver: bridge
